---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: grype-scan-source
  labels:
    apps.kadras.io/task: scan
    apps.kadras.io/scanner: grype
    apps.kadras.io/target: source
spec:
  description: Scans a given application source code directory with Grype.
  params:
    - name: source-url
    - name: source-revision
    - name: source-subpath
    - name: grype-args
      default:
        - "--only-fixed"
  workspaces:
    - name: source-dir
      mountPath: /workspace/source-dir
  steps:
    - name: prepare
      image: paketobuildpacks/build-jammy-base:0.1.47
      workingDir: /tekton/home
      securityContext:
        runAsNonRoot: true
      script: |-
        cd `mktemp -d`
        curl -SL $(params.source-url) | tar xvz -m
        cd $(params.source-subpath)
        mv * $(workspaces.source-dir.path)
    - name: scan
      image: anchore/grype:v0.59.1
      workingDir: $(workspaces.source-dir.path)
      args: ["dir:.", "$(params.grype-args[*])"]
