---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: grype-scan-image
  labels:
    apps.kadras.io/task: scan
    apps.kadras.io/scanner: grype
    apps.kadras.io/target: image
spec:
  description: Scans a given OCI image for vulnerabilities with Grype.
  params:
    - name: image
    - name: grype-args
      default:
        - "--only-fixed"
  steps:
    - name: scan
      image: anchore/grype
      args: ["$(params.image)", "$(params.grype-args[*])"]
