apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: tekton-catalog.packages.kadras.io.0.0.0
spec:
  licenses:
  - Apache 2.0
  refName: tekton-catalog.packages.kadras.io
  releaseNotes: https://github.com/kadras-io/tekton-catalog/releases
  releasedAt: null
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - git: {}
      template:
      - ytt:
          paths:
          - config
      - kbld: {}
  valuesSchema:
    openAPIv3: {}
  version: 0.0.0

---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  creationTimestamp: null
  name: tekton-catalog.packages.kadras.io
spec:
  categories:
  - build
  displayName: tekton-catalog
  longDescription: A set of Tekton pipelines and tasks used by the Kadras platform to support testing, scanning, delivering and deploying applications.
  maintainers:
  - name: Thomas Vitale
  providerName: Kadras
  shortDescription: A set of Tekton pipelines and tasks to use with the Kadras platform.
  supportDescription: Go to https://kadras.io for documentation and https://github.com/kadras-io/tekton-catalog
    for community support.

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    kctrl.carvel.dev/local-fetch-0: .
  creationTimestamp: null
  name: tekton-catalog
spec:
  packageRef:
    refName: tekton-catalog.packages.kadras.io
    versionSelection:
      constraints: 0.0.0
  serviceAccountName: kadras-install-sa
status:
  conditions: null
  friendlyDescription: ""
  observedGeneration: 0
